version: '2'

services:
  mysql:
    image: mysql:5.7   
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: test
      MYSQL_USER: sfadmin
      MYSQL_PASSWORD: pass42

  phpmyadmin:
    environment:
      PMA_HOST: mysql
    image: phpmyadmin/phpmyadmin
    links:
    - mysql
    ports:
    - 3000:80